# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "8118fb615ea3dd85214516d2e2fe05142f52750ab2a1da606a01f4a39458314f"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f6e1e0188ddde6be30262d2560f4daa8b258edfbe773d0707d2c93744128475a"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "13254ead42ee3bc90b36146d20d110a81d0d0e52d563db6f21fdf5e3b0f50b79"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9060ddcf95b5bbec8d81f44c656fd678eb563f883db49f9cb4c67ebff8919263"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
