# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "69d4a96ca9705261435399907a81679fa4fbfd68b2a15c59e67ab6e5e1231fbe"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7db45ab206ce9247111472bd3a02404e48cdc9c3884eb5cf24cf55da07777f39"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ff64278d59f03fb3744ad171e0fc98a47a7f25c865ba1629b57a7f3e43976ec"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7d9c6ebca6c9a9927ed482a539726354b9a6c76bd2323c48b482ecc1238170f2"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
