# This file was generated by GoReleaser. DO NOT EDIT.
cask "jira-mcp" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "bbbec0c4ca9609c31f7acead390f18c22457ca1ed7198bcf45ef62aaca372228"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7735b859a002e73f9d75697dec5090a329eecf9ef2aa58bf7ef8941e75f2a114"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "964def7de63b9f037adcaf06d5bbcd5c933062a4614d94cfc8c8ac777f738b2c"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec21ce60b83c3a384cb978a2f3f93a216dc3b9fec079895ef946bf310e5b824b"
      url "https://github.com/mmatczuk/jira-mcp/releases/download/v#{version}/jira-mcp_linux_arm64.tar.gz"
    end
  end

  name "jira-mcp"
  desc "JIRA MCP server — give your AI assistant full JIRA access"
  homepage "https://github.com/mmatczuk/jira-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jira-mcp"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jira-mcp"]
    end
  end

  # No zap stanza required

end
